//! `feedsign drift` (dig_ecosystem#3046): does the feed we actually SERVE describe the versions
//! that have actually been RELEASED?
//!
//! # The failure this exists to make loud
//!
//! The feed is regenerated by a 6-hour cron. A component that releases at 00:05 is therefore
//! invisible to every beacon until 06:00 — and *nothing turns red in the meantime*. The release
//! workflow succeeded. The Feed workflow succeeded, at its last scheduled tick. The manifest served
//! to users simply describes an older world, and no signal anywhere says so.
//!
//! The gap was measured three times in one day — after dig-node 0.122.1, after dig-app 12.16.0 /
//! dig-node 0.124.0, and after dig-app 12.17.0 — each needing a hand-run `gh workflow run feed.yml`,
//! and each time the served manifest's `generated` timestamp *predated* the release it was missing.
//! So it was genuinely stale, not merely lagging.
//!
//! # Why [`DoctorReport`] does not already catch this
//!
//! Doctor (dig_ecosystem#2115) asks *"can each component's declared assets be resolved from its
//! release?"*. In the #3046 outage the answer was **yes, for every component** — the releases were
//! perfect. What was wrong was the *published document*, which doctor never reads. Doctor validates
//! the INPUTS to a feed; drift validates the OUTPUT that beacons are being served. A feed can be
//! arbitrarily stale with a fully green doctor.
//!
//! # The check
//!
//! One predicate, per component:
//!
//! > the version this component's channel release supplies  ==  the version the live feed serves
//!
//! The left side comes from [`resolve_all`] — the SAME resolution [`crate::produce_feed`] performs —
//! so the check can never disagree with the signer about what a regenerated feed *would* contain.
//! The right side is the `version` field of the manifest fetched from its live URL. No signing key
//! and no asset downloads are involved, which is what lets this run every few minutes in an
//! unprivileged workflow.
//!
//! # Fails closed
//!
//! A component whose release cannot be resolved yields [`Drift::Unknown`], which counts AGAINST
//! [`DriftReport::is_current`]. The check's contract is *"I proved the feed matches the releases"*;
//! when it cannot prove that for a component it must not report current. Reporting "no drift"
//! because the left side was unavailable is precisely how a stale feed would slip past — one
//! unresolvable component would mask every other component's staleness.
//!
//! # This reads the manifest as data, not as a trust decision
//!
//! [`check_drift`] parses the served manifest without verifying its signature. That is deliberate
//! and is not a weakening: signature validity is proven before publication by the Feed job's
//! pinned-key keystone, and re-proven on every client by the beacon. A drift alarm answers a
//! different question — *does the published document describe the current release?* — and a forged
//! manifest that lied about versions would trip this check rather than evade it.
//!
//! # What it deliberately does NOT catch
//!
//! - A release re-uploaded with **different bytes under the same version**: the digests would change
//!   while the versions matched. Catching that needs the asset hashes, hence the downloads this
//!   check exists to avoid.
//! - A release that **never happened at all**. A stable job that silently skipped (the wrong-ref
//!   dispatch of dig_ecosystem#2125) leaves `releases/latest` on the old version, so the feed agrees
//!   with it and this check is honestly green. That is a different HOP of the same predicate —
//!   *declared* version vs *released* version — and it can only be checked in the releasing repo,
//!   which is why it is not here. See the crate docs and dig_ecosystem#3047.

use crate::channel::Channel;
use crate::config::FeedConfig;
use crate::error::FeedsignError;
use crate::source::ReleaseSource;
use crate::{resolve_all, ComponentResolution};
use dig_updater_trust::{Manifest, SignedManifest};

/// One component whose released version and served version do not agree — or cannot be compared.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Drift {
    /// The feed serves a version other than the one this channel's release supplies.
    ///
    /// Almost always the feed being *behind* a fresh release (the #3046 case), but an `in_feed`
    /// *ahead* of `released` is reported identically — that means a release was deleted, yanked, or
    /// retargeted after the feed was signed, which is at least as alarming.
    Mismatch {
        /// The component name from `feed-config.json`.
        component: String,
        /// The version the channel's release currently supplies.
        released: String,
        /// The version the live manifest actually serves.
        in_feed: String,
    },
    /// The component resolves to a release, but the live manifest does not carry it at all — a
    /// newly configured component the feed has never been regenerated to include.
    Absent {
        /// The component name from `feed-config.json`.
        component: String,
        /// The version the channel's release currently supplies.
        released: String,
    },
    /// The component's released version could not be resolved, so the comparison could not be made.
    ///
    /// This is doctor's failure to diagnose, not drift's — but it MUST count against the verdict, or
    /// one unresolvable component would let the check report "current" while the feed was stale.
    Unknown {
        /// The component name from `feed-config.json`.
        component: String,
        /// Why its released version could not be resolved.
        reason: String,
    },
}

impl Drift {
    /// The component this drift concerns.
    #[must_use]
    pub fn component(&self) -> &str {
        match self {
            Drift::Mismatch { component, .. }
            | Drift::Absent { component, .. }
            | Drift::Unknown { component, .. } => component,
        }
    }

    /// A one-line, operator-facing description naming both sides of the disagreement.
    #[must_use]
    pub fn describe(&self) -> String {
        match self {
            Drift::Mismatch {
                component,
                released,
                in_feed,
            } => format!("{component}: released {released}, but the feed serves {in_feed}"),
            Drift::Absent {
                component,
                released,
            } => format!("{component}: released {released}, but the feed does not carry it at all"),
            Drift::Unknown { component, reason } => {
                format!("{component}: released version could not be resolved — {reason}")
            }
        }
    }
}

/// Compare each component's resolved release against the version a manifest serves.
///
/// Pure: no clock, no network. Results follow `resolutions` order (configuration order), so the
/// report is stable run to run.
///
/// A component present in `served` but absent from `resolutions` is NOT reported: that is a
/// component dropped from the configuration, which the next regeneration removes on its own and
/// which does not make the feed wrong about anything still configured.
#[must_use]
pub fn compare(resolutions: &[ComponentResolution], served: &Manifest) -> Vec<Drift> {
    resolutions
        .iter()
        .filter_map(|resolution| {
            let component = resolution.name.clone();
            let released = match &resolution.outcome {
                Ok(resolved) => resolved.version.clone(),
                Err(error) => {
                    return Some(Drift::Unknown {
                        component,
                        reason: error.to_string(),
                    })
                }
            };
            match served.component(&component) {
                Some(in_feed) if in_feed.version == released => None,
                Some(in_feed) => Some(Drift::Mismatch {
                    component,
                    released,
                    in_feed: in_feed.version.clone(),
                }),
                None => Some(Drift::Absent {
                    component,
                    released,
                }),
            }
        })
        .collect()
}

/// The outcome of one drift check against one channel's live feed.
#[derive(Debug, Clone)]
pub struct DriftReport {
    /// The channel that was checked.
    pub channel: Channel,
    /// The manifest URL that was read.
    pub manifest_url: String,
    /// The served manifest's `generated` timestamp. Reported for diagnosis: a `generated` that
    /// predates a missing release is the signature of a feed that never regenerated, as distinct
    /// from one that regenerated and resolved something unexpected.
    pub generated: u64,
    /// Every configured component's `(name, served_version_or_absent)` — the full picture, so the
    /// report is legible even when there is no drift at all.
    pub served: Vec<(String, Option<String>)>,
    /// The disagreements found. Empty means the feed is current.
    pub drifts: Vec<Drift>,
}

impl DriftReport {
    /// Whether the live feed provably describes exactly the versions currently released.
    ///
    /// False when ANY component drifted OR could not be compared ([`Drift::Unknown`]) — this is the
    /// fail-closed half of the contract.
    #[must_use]
    pub fn is_current(&self) -> bool {
        self.drifts.is_empty()
    }

    /// Whether regenerating the feed would plausibly FIX what was found.
    ///
    /// True when at least one drift is a [`Drift::Mismatch`] or [`Drift::Absent`] — a stale
    /// published document, which is exactly what a fresh signing pass replaces.
    ///
    /// False when the only findings are [`Drift::Unknown`]: a release that cannot be resolved will
    /// not resolve any better for the signer, so a regeneration would fail the same way. This
    /// distinction is what keeps an automated responder from dispatching the Feed workflow every
    /// polling interval against a fault regeneration cannot clear — the runs would queue behind the
    /// `feed` concurrency group and pile up indefinitely.
    #[must_use]
    pub fn is_regenerable(&self) -> bool {
        self.drifts
            .iter()
            .any(|d| matches!(d, Drift::Mismatch { .. } | Drift::Absent { .. }))
    }

    /// The machine-readable report (§6.2): the verdict, whether a regeneration would fix it, and
    /// every drift with both sides named. Stable field names — an automated responder keys on
    /// `regenerable` to decide whether to dispatch the Feed workflow.
    #[must_use]
    pub fn to_json(&self) -> String {
        let drifts: Vec<serde_json::Value> = self
            .drifts
            .iter()
            .map(|drift| match drift {
                Drift::Mismatch {
                    component,
                    released,
                    in_feed,
                } => serde_json::json!({
                    "kind": "mismatch",
                    "component": component,
                    "released": released,
                    "in_feed": in_feed,
                }),
                Drift::Absent {
                    component,
                    released,
                } => serde_json::json!({
                    "kind": "absent",
                    "component": component,
                    "released": released,
                }),
                Drift::Unknown { component, reason } => serde_json::json!({
                    "kind": "unknown",
                    "component": component,
                    "reason": reason,
                }),
            })
            .collect();
        serde_json::json!({
            "channel": self.channel.as_str(),
            "manifest_url": self.manifest_url,
            "generated": self.generated,
            "current": self.is_current(),
            "regenerable": self.is_regenerable(),
            "drifts": drifts,
        })
        .to_string()
    }

    /// A legible, secret-free report — the verdict, one line per component, then each drift.
    #[must_use]
    pub fn render(&self) -> String {
        let mut out = format!(
            "feed drift — channel: {}\n  manifest: {}\n  generated: {}\n",
            self.channel.as_str(),
            self.manifest_url,
            self.generated
        );
        for (name, version) in &self.served {
            match version {
                Some(v) => out.push_str(&format!("  serves {name} {v}\n")),
                None => out.push_str(&format!("  serves {name} (absent)\n")),
            }
        }
        for drift in &self.drifts {
            out.push_str(&format!("  DRIFT {}\n", drift.describe()));
        }
        if self.is_current() {
            out.push_str("the live feed is CURRENT with every configured component's release.\n");
        } else {
            out.push_str(&format!(
                "the live feed is BEHIND: {} component(s) disagree with their release.\n",
                self.drifts.len()
            ));
        }
        out
    }
}

/// Resolve every configured component's released version for `channel` and compare it against the
/// manifest currently served at `manifest_url`.
///
/// Secret-free: it fetches release metadata plus one small JSON document, never downloads an
/// artifact and never signs.
///
/// # Errors
///
/// [`FeedsignError`] if the live manifest cannot be fetched or is not a well-formed signed manifest.
/// Fails closed: an unreadable feed is an error, never "no drift". Per-component resolution
/// failures do NOT error — they surface as [`Drift::Unknown`], so one bad component still leaves the
/// rest of the feed checked.
pub fn check_drift(
    config: &FeedConfig,
    source: &dyn ReleaseSource,
    channel: Channel,
    manifest_url: &str,
) -> Result<DriftReport, FeedsignError> {
    let resolutions = resolve_all(config, source, channel);

    let bytes = source.download(manifest_url)?;
    let text = String::from_utf8(bytes).map_err(|e| FeedsignError::Github {
        url: manifest_url.to_string(),
        detail: format!("served manifest is not UTF-8: {e}"),
    })?;
    let served = SignedManifest::from_json(&text).map_err(|e| FeedsignError::Github {
        url: manifest_url.to_string(),
        detail: format!("served manifest is not a well-formed signed manifest: {e}"),
    })?;

    let drifts = compare(&resolutions, &served.manifest);
    let served_versions = resolutions
        .iter()
        .map(|r| {
            (
                r.name.clone(),
                served
                    .manifest
                    .component(&r.name)
                    .map(|c| c.version.clone()),
            )
        })
        .collect();

    Ok(DriftReport {
        channel,
        manifest_url: manifest_url.to_string(),
        generated: served.manifest.generated,
        served: served_versions,
        drifts,
    })
}

/// The live manifest URL for `channel` under a feed base (`https://updates.dig.net/v1`).
///
/// Kept here so the checker and the workflow cannot disagree about which document is authoritative
/// for a channel — the same `/v1/{channel}/manifest.json` shape `feed.yml` publishes to (SPEC §10).
#[must_use]
pub fn manifest_url_for(feed_base: &str, channel: Channel) -> String {
    format!(
        "{}/{}/manifest.json",
        feed_base.trim_end_matches('/'),
        channel.as_str()
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ResolvedComponent;
    use dig_updater_trust::Component;

    fn manifest_with(components: &[(&str, &str)]) -> Manifest {
        Manifest {
            schema: 2,
            root_version: 1,
            sequence: 1_000,
            generated: 1_762_000_000,
            expires: 1_762_043_200,
            rollback_floor_build: 0,
            components: components
                .iter()
                .map(|(name, version)| Component {
                    name: (*name).to_string(),
                    version: (*version).to_string(),
                    build: 1,
                    artifacts: vec![],
                })
                .collect(),
        }
    }

    fn resolved(pairs: &[(&str, &str)]) -> Vec<ComponentResolution> {
        pairs
            .iter()
            .map(|(name, version)| ComponentResolution {
                name: (*name).to_string(),
                outcome: Ok(ResolvedComponent {
                    version: (*version).to_string(),
                    build: 1,
                    artifacts: vec![],
                }),
            })
            .collect()
    }

    #[test]
    fn a_feed_serving_every_released_version_has_no_drift() {
        let drifts = compare(
            &resolved(&[("dig-node", "0.124.0"), ("dig-app", "12.17.0")]),
            &manifest_with(&[("dig-node", "0.124.0"), ("dig-app", "12.17.0")]),
        );
        assert!(drifts.is_empty(), "expected no drift, got {drifts:?}");
    }

    /// THE #3046 CASE, as measured: dig-app released 12.17.0 while the feed still served 12.16.0.
    /// Without this check that state is invisible — every workflow involved is green.
    #[test]
    fn a_feed_behind_a_fresh_release_is_reported_as_drift() {
        let drifts = compare(
            &resolved(&[("dig-node", "0.124.0"), ("dig-app", "12.17.0")]),
            &manifest_with(&[("dig-node", "0.124.0"), ("dig-app", "12.16.0")]),
        );
        assert_eq!(
            drifts,
            vec![Drift::Mismatch {
                component: "dig-app".into(),
                released: "12.17.0".into(),
                in_feed: "12.16.0".into(),
            }]
        );
        assert_eq!(
            drifts[0].describe(),
            "dig-app: released 12.17.0, but the feed serves 12.16.0"
        );
    }

    /// A feed AHEAD of `releases/latest` means a release was deleted or retargeted after signing.
    /// It must not read as "current" merely because the check was written expecting staleness.
    #[test]
    fn a_feed_ahead_of_the_release_is_also_drift() {
        let drifts = compare(
            &resolved(&[("dig-node", "0.124.0")]),
            &manifest_with(&[("dig-node", "0.125.0")]),
        );
        assert_eq!(
            drifts,
            vec![Drift::Mismatch {
                component: "dig-node".into(),
                released: "0.124.0".into(),
                in_feed: "0.125.0".into(),
            }]
        );
    }

    #[test]
    fn a_configured_component_missing_from_the_feed_is_drift() {
        let drifts = compare(
            &resolved(&[("dig-node", "0.124.0"), ("dig-app", "12.17.0")]),
            &manifest_with(&[("dig-node", "0.124.0")]),
        );
        assert_eq!(
            drifts,
            vec![Drift::Absent {
                component: "dig-app".into(),
                released: "12.17.0".into(),
            }]
        );
    }

    /// A component the feed still carries but the config has dropped is not the feed being wrong
    /// about anything configured, and must not redden the check forever.
    #[test]
    fn a_component_only_in_the_feed_is_not_drift() {
        let drifts = compare(
            &resolved(&[("dig-node", "0.124.0")]),
            &manifest_with(&[("dig-node", "0.124.0"), ("retired", "1.0.0")]),
        );
        assert!(drifts.is_empty(), "expected no drift, got {drifts:?}");
    }

    /// THE FAIL-CLOSED PROPERTY. An unresolvable component must not be silently skipped: if it
    /// were, this exact input — one unresolvable component beside a genuinely stale one — would
    /// report the feed current while it was six hours behind.
    #[test]
    fn an_unresolvable_component_is_drift_not_silence() {
        let mut resolutions = resolved(&[("dig-app", "12.17.0")]);
        resolutions.insert(
            0,
            ComponentResolution {
                name: "dig-node".to_string(),
                outcome: Err(FeedsignError::Fetch {
                    url: "https://api.github.com/repos/DIG-Network/dig-node/releases/latest".into(),
                    detail: "503 Service Unavailable".into(),
                }),
            },
        );
        let drifts = compare(&resolutions, &manifest_with(&[("dig-app", "12.17.0")]));
        assert_eq!(drifts.len(), 1, "the unresolvable component must be listed");
        assert!(matches!(drifts[0], Drift::Unknown { .. }));
        assert_eq!(drifts[0].component(), "dig-node");
        assert!(drifts[0].describe().contains("503"));
    }

    /// Nightly versions are full prerelease strings; the comparison is exact, so a nightly whose
    /// build date moved is drift even though its semver core did not.
    #[test]
    fn nightly_prerelease_versions_compare_exactly() {
        let drifts = compare(
            &resolved(&[("dig-node", "0.125.0-nightly.20260811.def5678")]),
            &manifest_with(&[("dig-node", "0.125.0-nightly.20260810.abc1234")]),
        );
        assert_eq!(drifts.len(), 1, "a moved nightly build date is drift");
    }

    #[test]
    fn drifts_are_reported_in_configuration_order() {
        let drifts = compare(
            &resolved(&[("a", "2"), ("b", "2"), ("c", "2")]),
            &manifest_with(&[("a", "1"), ("b", "1"), ("c", "1")]),
        );
        let names: Vec<&str> = drifts.iter().map(Drift::component).collect();
        assert_eq!(names, vec!["a", "b", "c"]);
    }

    fn report_with(drifts: Vec<Drift>) -> DriftReport {
        DriftReport {
            channel: Channel::Stable,
            manifest_url: "https://updates.dig.net/v1/stable/manifest.json".into(),
            generated: 1_762_000_000,
            served: vec![("dig-app".into(), Some("12.16.0".into()))],
            drifts,
        }
    }

    #[test]
    fn the_render_states_the_verdict_and_names_each_drift() {
        let report = report_with(vec![Drift::Mismatch {
            component: "dig-app".into(),
            released: "12.17.0".into(),
            in_feed: "12.16.0".into(),
        }]);
        assert!(!report.is_current());
        let rendered = report.render();
        assert!(rendered.contains("is BEHIND"), "{rendered}");
        assert!(rendered.contains("12.17.0"), "{rendered}");
        assert!(rendered.contains("12.16.0"), "{rendered}");
        assert!(rendered.contains("generated: 1762000000"), "{rendered}");
    }

    #[test]
    fn a_current_feed_renders_as_current() {
        let report = report_with(vec![]);
        assert!(report.is_current());
        assert!(report.render().contains("is CURRENT"));
    }

    /// An `Unknown` alone must flip the verdict — the fail-closed contract at the report level, not
    /// just in `compare`.
    #[test]
    fn an_unknown_alone_makes_the_report_not_current() {
        let report = report_with(vec![Drift::Unknown {
            component: "dig-node".into(),
            reason: "503".into(),
        }]);
        assert!(
            !report.is_current(),
            "an uncomparable component must not read as current"
        );
    }

    /// A stale published document is exactly what a fresh signing pass replaces, so the responder
    /// should dispatch.
    #[test]
    fn a_stale_feed_is_regenerable() {
        let report = report_with(vec![Drift::Mismatch {
            component: "dig-app".into(),
            released: "12.17.0".into(),
            in_feed: "12.16.0".into(),
        }]);
        assert!(report.is_regenerable());
        let absent = report_with(vec![Drift::Absent {
            component: "dig-app".into(),
            released: "12.17.0".into(),
        }]);
        assert!(absent.is_regenerable());
    }

    /// THE QUEUE-BOMB GUARD. A release that cannot be resolved will not resolve any better for the
    /// signer, so dispatching on it every polling interval would pile runs up behind the `feed`
    /// concurrency group forever. It must be reported (not current) but NOT acted on.
    #[test]
    fn an_unresolvable_component_alone_is_not_regenerable() {
        let report = report_with(vec![Drift::Unknown {
            component: "dig-node".into(),
            reason: "503".into(),
        }]);
        assert!(
            !report.is_current(),
            "it must still be reported as not current"
        );
        assert!(
            !report.is_regenerable(),
            "regeneration cannot fix an unresolvable release; dispatching on it queue-bombs the \
             Feed workflow"
        );
    }

    /// A genuinely stale component beside an unresolvable one still warrants the dispatch — the
    /// staleness is real and regeneration fixes that half.
    #[test]
    fn a_stale_component_beside_an_unresolvable_one_is_still_regenerable() {
        let report = report_with(vec![
            Drift::Unknown {
                component: "dig-node".into(),
                reason: "503".into(),
            },
            Drift::Mismatch {
                component: "dig-app".into(),
                released: "12.17.0".into(),
                in_feed: "12.16.0".into(),
            },
        ]);
        assert!(report.is_regenerable());
    }

    #[test]
    fn a_current_feed_is_not_regenerable() {
        assert!(!report_with(vec![]).is_regenerable());
    }

    #[test]
    fn the_json_report_names_both_sides_and_the_responder_signal() {
        let report = report_with(vec![Drift::Mismatch {
            component: "dig-app".into(),
            released: "12.17.0".into(),
            in_feed: "12.16.0".into(),
        }]);
        let parsed: serde_json::Value =
            serde_json::from_str(&report.to_json()).expect("the report is valid JSON");
        assert_eq!(parsed["current"], serde_json::json!(false));
        assert_eq!(parsed["regenerable"], serde_json::json!(true));
        assert_eq!(parsed["channel"], serde_json::json!("stable"));
        assert_eq!(parsed["generated"], serde_json::json!(1_762_000_000u64));
        assert_eq!(parsed["drifts"][0]["kind"], serde_json::json!("mismatch"));
        assert_eq!(
            parsed["drifts"][0]["released"],
            serde_json::json!("12.17.0")
        );
        assert_eq!(parsed["drifts"][0]["in_feed"], serde_json::json!("12.16.0"));
    }

    /// The responder keys on `regenerable`; an `unknown`-only report must carry it as false in the
    /// JSON too, not merely in the Rust API.
    #[test]
    fn the_json_report_withholds_the_responder_signal_for_unknown_only() {
        let report = report_with(vec![Drift::Unknown {
            component: "dig-node".into(),
            reason: "503".into(),
        }]);
        let parsed: serde_json::Value = serde_json::from_str(&report.to_json()).unwrap();
        assert_eq!(parsed["current"], serde_json::json!(false));
        assert_eq!(parsed["regenerable"], serde_json::json!(false));
        assert_eq!(parsed["drifts"][0]["kind"], serde_json::json!("unknown"));
    }

    #[test]
    fn manifest_urls_follow_the_published_channel_paths() {
        assert_eq!(
            manifest_url_for("https://updates.dig.net/v1", Channel::Stable),
            "https://updates.dig.net/v1/stable/manifest.json"
        );
        assert_eq!(
            manifest_url_for("https://updates.dig.net/v1/", Channel::Nightly),
            "https://updates.dig.net/v1/nightly/manifest.json"
        );
    }
}
